---
- import_playbook: playbooks/verify_access.yml
- import_playbook: playbooks/install_k3s.yml
- import_playbook: playbooks/install_helm.yml
- import_playbook: playbooks/install_traefik.yml
#- import_playbook: playbooks/install_argocd.yml
