---
- name: Ensure Python Kubernetes library is installed
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3
    extra_args: --break-system-packages
  become: true

- name: Add the Bitnami Helm repository
  kubernetes.core.helm_repository:
    name: "{{ argocd_helm_repo_name }}"
    repo_url: "{{ argocd_helm_repo_url }}"

- name: Create the ArgoCD namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ argocd_namespace }}"
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Copy ArgoCD values file to the target machine
  ansible.builtin.copy:
    src: "{{ argocd_helm_values_file }}"
    dest: "/tmp/argocd_values.yaml"

- name: Install ArgoCD via Helm
  kubernetes.core.helm:
    name: "{{ argocd_release_name }}"
    chart_ref: "{{ argocd_helm_repo_name }}/{{ argocd_chart_name }}"
    namespace: "{{ argocd_namespace }}"
    release_state: present
    values_files:
      - "/tmp/argocd_values.yaml"
