# Namespace for ArgoCD
argocd_namespace: argocd

# Bitnami Helm Chart details
argocd_helm_repo_name: bitnami
argocd_helm_repo_url: https://charts.bitnami.com/bitnami
argocd_chart_name: argo-cd
argocd_release_name: argocd
argocd_helm_values_file: "{{ role_path }}/files/helm-values.yaml"
