---
dependencies: []
galaxy_info:
  author: enmanuelmoreira
  role_name: traefik
  description: Configuring Traefik role.
  license: license (MIT)
  min_ansible_version: "2.7"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
